### ISSUE TITLE
Concatenation should be corrected

### ISSUE THREAD

**Issue by younes-io** [aybbou/Rayak#20]
These lines should be corrected. No need to concatenate : 

https://github.com/aybbou/Rayak/blob/master/src/Db/CreatorBundle/Creator/Creator.php#L84

https://github.com/aybbou/Rayak/blob/master/src/Db/CreatorBundle/Creator/Creator.php#L130

https://github.com/aybbou/Rayak/blob/master/src/Db/CreatorBundle/Creator/Creator.php#L137

https://github.com/aybbou/Rayak/blob/master/src/Db/CreatorBundle/Creator/Creator.php#L192

https://github.com/aybbou/Rayak/blob/master/src/Db/CreatorBundle/Creator/Creator.php#L200

**Comment by aybbou** [comment]
Ok will do that !
